language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
install:
  - pip install coveralls
script:
  - python -m compileall -f .
  - coverage run --source=flags setup.py test
after_success:
  coveralls
notifications:
  email: false
